[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
decorations = "none"
opacity = 0.99
startup_mode = "maximized"

[mouse]
hide_when_typing = true

[font]
size = 14
normal.family = "JetBrains Mono"

[colors.primary]
background = "#131021"

[colors.normal]
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"
