[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 5

[font]
normal.family = "DroidSansM Nerd Font"
size = 11

[colors]
transparent_background_colors = true

[colors.primary]
background = "#161616"
foreground = "#f2f4f8"

[colors.normal]
black = "#282828"
red = "#b1001e"
green = "#25be6a"
yellow = "#e6c000"
blue = "#78a9ff"
magenta = "#be95ff"
cyan = "#33b1ff"
white = "#dfdfe0"
