format = """
$username\
@$hostname\
$directory\
$git_branch\
$golang\
$terraform\
$rust\
$python\
${custom.ansible}\
$line_break\
$character
"""

# Set the timeout for command execution
command_timeout=2000

# Set to true to avoid a two-line prompt
[line_break]
disabled = false

# Set disabled to true when using a one-line prompt for more aesthetically pleasing results
[character]
success_symbol = '[└─>](bold green)'
error_symbol = '[└─>](bold red)'
format = '$symbol '
disabled = false

[username]
style_user = "fg:2"
style_root = "red bold"
format="[$user]($style)"
show_always = true
disabled = false

[hostname]
ssh_only = false
format = "[$hostname](cyan) "
disabled = false

[directory]
style = 'fg:#39466b'
format = '[\[ $path \] ]($style)'
truncation_length = 6
truncation_symbol = '…/'

[git_branch]
symbol = ''
style = 'purple'
format = 'on [$symbol $branch ]($style)'

[golang]
symbol = ''
style = 'fg:#00ADD8'
format = 'via [$symbol ($version) ]($style)'

[python]
symbol = ''
style = 'yellow'
format = 'via [$symbol ($version) ]($style)'

[rust]
symbol = ''
style = 'fg:#2C3E50'
format = 'via [$symbol ($version) ]($style)'

[terraform]
symbol = '󱁢'
style = 'fg:#7B42BC'
format = 'via [$symbol ($version) ]($style)'

[custom.ansible]
symbol = "󱂚"
description = "Ansible Core version"
files = [ "ansible.cfg" ]
style = 'red'
format = "via [$symbol $output]($style) "
shell = '/bin/bash'
command = 'echo -n $(ansible --version 2>/dev/null | grep -oP "(?<=core )[\d\.]+")'
