# Key bindings for taking screenshots
#
# Overwrite: /usr/share/sway/config.d/60-bindings-screenshot.conf
#
# Requires:  grimshot

# Set mod to super key
set $mod Mod4

bindsym {
    # Screenshot and clipboard
    $mod+Print exec grimshot --notify copy area

    # Capture the currently active output
    Print exec grimshot --notify save output
}
