# Idle and lock configuration
#
# Overwrite: /usr/share/sway/config.d/90-swayidle.conf
#
# Requires:  swayidle
# Requires:  swaylock
# Requires:  /usr/bin/pkill, /usr/bin/pgrep

exec LT="$lock_timeout" ST="$screen_timeout" LT=${LT:-1200} ST=${ST:-300} && \
    swayidle -w \
        timeout $LT 'swaylock -f' \
        timeout $((LT + ST)) 'swaymsg "output * power off"' \
                      resume 'swaymsg "output * power on"'  \
        timeout $ST 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power off"' \
             resume 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power on"'  \
        before-sleep 'swaylock -f' \
        lock 'swaylock -f' \
        unlock 'pkill -xu "$USER" -SIGUSR1 swaylock'
