[settings]
dotfiles.root = "~/dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]
"~/.config/fish" = "dotfiles/devcontainer/fish"
"~/.config/nvim" = "dotfiles/dot_config/nvim"
"~/.pi/agent/extensions" = "dotfiles/devcontainer/pi/extensions"
"~/.pi/agent/*.json" = "dotfiles/devcontainer/pi/*.json"

[tools]
neovim = "latest"
fzf = "latest"
direnv = "latest"
zoxide = "latest"
tree-sitter = "latest"
pi = "latest"
node = "latest"

[tasks.bootstrap]
run = 'nvim --headless "+qa"'
