# Base settings
set  -g  default-terminal   "screen-256color"
set  -ga terminal-overrides ",xterm-256color*:Tc"
set  -g  base-index         1
setw -g  pane-base-index    1
set  -g  status-keys        vi
set  -g  mode-keys          vi
set  -g  mouse              on
set  -g  focus-events       off
setw -g  aggressive-resize  off
setw -g  clock-mode-style   24
set  -sg escape-time        0
set  -g  history-limit      5000
set  -g  renumber-windows   on

# Source tmux config file
bind-key R source-file ~/.config/tmux/tmux.conf

# Settings for vi visual mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection

# Copy to clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe 'xclip -in -selection clipboard'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe

# Set visual mode text highlighting colors
set-option -g mode-style 'bg=#4c4c4c'

# Vim-like pane switching
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# Resize panes with arrow keys
bind Up resize-pane -U 2
bind Down resize-pane -D 2
bind Left resize-pane -L 2
bind Right resize-pane -R 2

# Switch between tmux windows with <tab>
bind-key Tab next-window

# Modify status bar
set-option -g status-position bottom
set-option -g status-style 'bg=#0e1415,fg=#424a4b'
set-option -g status-left-length 50
set-option -g status-justify left
set-option -g status-right ""

# Pane borders
set -g pane-border-style 'fg=colour8'
set -g pane-active-border-style 'fg=green'

# Session management with custom scripts
bind-key -r f run-shell "~/.local/bin/tmux-sessionizer.sh"
bind-key -r w run-shell "~/.local/bin/tmux-sessions.sh"

# Legendary Tmux Pane to Vim Buffer
bind-key i run-shell "~/.local/bin/tmux-pane-edit.sh"
