if status is-interactive
    fish_add_path /usr/local/go/bin $HOME/go/bin $HOME/.local/bin $HOME/bin $HOME/.cargo/bin
    set -x EDITOR nvim
    alias vim="nvim"
    alias vi="nvim"
    alias n="nvim"
end
direnv hook fish | source
kubectl completion fish | source
starship init fish | source
zoxide init --cmd cd fish | source
fzf --fish | source

# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

# Only source this once.
if [ -n "$__HM_SESS_VARS_SOURCED" ]
  return
end
set -gx __HM_SESS_VARS_SOURCED 1
set -gx EDITOR nvim
set -gx VISUAL nvim
set -gx STARSHIP_CONFIG '/home/dstrobel/.config/starship.toml'
set -gx TMUX_TMPDIR (test -n "$XDG_RUNTIME_DIR" && echo "$XDG_RUNTIME_DIR" || echo '/run/user/'(id -u | string collect; or echo))
end
setup_hm_session_vars

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases
    alias gbws git-branch-worktree-switch
    alias lla 'ls -la'
    alias t /nix/store/wf39gf8nhzhkd8akwqhpah0fx9n4m03b-tmux-open/bin/tmux-open
    alias vimdiff 'nvim -d'

    # Interactive shell initialisation
    fzf --fish | source
    lasergraph-timecode-importer completions fish | source
    zoxide init fish --cmd cd | source
    starship init fish | source

    # Keychain integration
    SHELL=fish eval (keychain --eval --quiet id_ed25519 id_ed25519_vault-prod)

    # add completions generated by Home Manager to $fish_complete_path
    # begin
    #     set -l joined (string join " " $fish_complete_path)
    #     set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
    #     set -l post_joined (string replace $prev_joined "" $joined)
    #     set -l prev (string split " " (string trim $prev_joined))
    #     set -l post (string split " " (string trim $post_joined))
    #     set fish_complete_path $prev "/home/dstrobel/.local/share/fish/home-manager/generated_completions" $post
    # end

    direnv hook fish | source
end
