# -*- conf -*-

# Set default shell
shell=/usr/bin/fish

font=JetBrainsMono NF:size=16

[security]
osc52=enabled

[bell]
system=yes
urgent=no
notify=no
visual=no
command=no
command-focused=no

[desktop-notifications]
command=notify-send --wait --app-name ${app-id} --icon ${app-id} --category ${category} --urgency ${urgency} --expire-time ${expire-time} --hint STRING:image-path:${icon} --hint BOOLEAN:suppress-sound:${muted} --hint STRING:sound-name:${sound-name} --replace-id ${replace-id} ${action-argument} --print-id -- ${title} ${body}

[scrollback]
lines=1000

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[touch]
long-press-delay=400

[colors]
alpha=1.0
background=0e1415
foreground=ffffff

## Normal/regular colors (color palette 0-7)
regular0=000000  # black
regular1=d2322d  # red
regular2=6abf40  # green
regular3=cd974b  # yellow
regular4=217ebc  # blue
regular5=9b3596  # magenta
regular6=178f79  # cyan
regular7=cecece  # white

## Bright colors (color palette 8-15)
# bright0=616161   # bright black
# bright1=ff4d51   # bright red
# bright2=35d450   # bright green
# bright3=e9e836   # bright yellow
# bright4=5dc5f8   # bright blue
# bright5=feabf2   # bright magenta
# bright6=24dfc4   # bright cyan
# bright7=ffffff   # bright white

[csd]
# preferred=server
# size=26
# font=<primary font>
# color=<foreground color>
# hide-when-maximized=no
# double-click-to-maximize=yes
# border-width=0
# border-color=<csd.color>
# button-width=26
# button-color=<background color>
# button-minimize-color=<regular4>
# button-maximize-color=<regular2>
# button-close-color=<regular1>

[key-bindings]
scrollback-up-page=Shift+Page_Up Shift+KP_Page_Up
scrollback-up-half-page=none
scrollback-up-line=none
scrollback-down-page=Shift+Page_Down Shift+KP_Page_Down
scrollback-down-half-page=none
scrollback-down-line=none
scrollback-home=none
scrollback-end=none
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
primary-paste=Shift+Insert
search-start=Control+Shift+r
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
spawn-terminal=Control+Shift+n
minimize=none
maximize=none
fullscreen=none
pipe-visible=[sh -c "xurls | fuzzel | xargs -r firefox"] none
pipe-scrollback=[sh -c "xurls | fuzzel | xargs -r firefox"] none
pipe-selected=[xargs -r firefox] none
pipe-command-output=[wl-copy] none # Copy last command's output to the clipboard
show-urls-launch=Control+Shift+o
show-urls-copy=none
show-urls-persistent=none
prompt-prev=Control+Shift+z
prompt-next=Control+Shift+x
unicode-input=Control+Shift+u
color-theme-switch-1=none
color-theme-switch-2=none
color-theme-toggle=none
noop=none
quit=none
